#! /bin/bash
#1、判断参数是否传入
if [ $# -lt 1 ]
then
	echo "必须输入一个参数..."
	exit
fi
#2、匹配参数执行逻辑
case $1 in
"start")
	for host in hadoop102 hadoop103 hadoop104
	do
		echo "==============start $host kafka===================="
		ssh $host "/opt/module/kafka/bin/kafka-server-start.sh -daemon /opt/module/kafka/config/server.properties"
	done
;;
"stop")
	for host in hadoop102 hadoop103 hadoop104
	do
		echo "==============stop $host kafka===================="
		ssh $host "/opt/module/kafka/bin/kafka-server-stop.sh"
	done
;;
*)
	echo "参数传输错误...."
;;
esac