#! /bin/bash
#1、判断参数是否传入
if [ $# -lt 1 ]
then
	echo "必须传入参数..."
	exit
fi
#2、根据参数匹配执行
case $1 in
"start")
	for host in hadoop102 hadoop103 hadoop104
	do
		echo "==========start $host zookeeper============="
		ssh $host "/opt/module/zookeeper/bin/zkServer.sh start"
	done
;;
"stop")
	for host in hadoop102 hadoop103 hadoop104
	do
		echo "==========stop $host zookeeper============="
		ssh $host "/opt/module/zookeeper/bin/zkServer.sh stop"
	done
;;
"status")
	for host in hadoop102 hadoop103 hadoop104
	do
		echo "==========status $host zookeeper============="
		ssh $host "/opt/module/zookeeper/bin/zkServer.sh status"
	done
;;
*)
	echo "参数传入错误...."
;;
esac